unbind-key C-b
set -g prefix C-a

set -g mouse on
set -g mode-keys vi
set -g extended-keys on
set -g extended-keys-format csi-u
set -g history-limit 20000
set -sg escape-time 0

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind-key C-a last-window
bind-key a send-prefix
bind-key Y previous-window
bind-key O next-window

unbind-key Up
unbind-key Down
unbind-key Left
unbind-key Right

# Unbind vi directional ergodox keys
unbind-key y
unbind-key n
unbind-key e
unbind-key o
unbind-key C-y
unbind-key C-n
unbind-key C-e
unbind-key C-o

# Set up key for vi style visual select and copy
bind-key P paste-buffer 
bind-key -T copy-mode-vi y send-keys -X cursor-left
bind-key -T copy-mode-vi n send-keys -X cursor-down
bind-key -T copy-mode-vi e send-keys -X cursor-up
bind-key -T copy-mode-vi o send-keys -X cursor-right
bind-key -T copy-mode-vi Y send-keys -X top-line
bind-key -T copy-mode-vi N send-keys -X scroll-down
bind-key -T copy-mode-vi E send-keys -X scroll-up
bind-key -T copy-mode-vi O send-keys -X bottom-line
bind-key -T copy-mode-vi h send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Set up keys to switch panes
bind-key -r n select-pane -D
bind-key -r e select-pane -U
bind-key -r y select-pane -L
bind-key -r o select-pane -R

# Set up keys to resize panes
bind-key -r C-n resize-pane -D 4
bind-key -r C-e resize-pane -U 4
bind-key -r C-y resize-pane -L 4
bind-key -r C-o resize-pane -R 4

# Set status bar
set -g status-bg black
set -g status-fg white
set -g status-left ''
set -g status-right '#[fg=yellow]%Y-%m-%d %H:%M'
set -g status-right-length 50

set -g pane-active-border-style 'bg=colour0,fg=colour1'
set -g pane-border-style 'bg=colour0,fg=colour3'

set -g window-style 'bg=colour0'
set -g window-active-style 'bg=colour0'

set -g window-status-current-style 'bg=colour0,fg=colour3'
set -g window-status-style 'bg=colour0,fg=white'
